version: '3.9'

services:
  ivcho-bazata:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=7400
      - POSTGRES_USER=ivcho
      - POSTGRES_DB=baza